### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by xrwang** [xrwang/thenuhanzi#4]
## Social

- [ ] Post more images of ways that people have bypassed censorship onto instagram
- [ ] Pinterest board of made up characters

## Design

- [ ] Figure out which radicals will be used (SVG)
     - [ ] Remake SVGs of radicals with their variants 
     - [ ] Annotate with meanings in title 
- [ ] Figure out strokes that are needed for the stroke section 
- [ ] strokes

## Code 
- [ ] Port the repo to use templating so that site can exist on gh-pages 
- [ ] Move Type your own onto side 
- [ ] Mouseover for SVGs
- [ ] Canvas style into box
